### ISSUE TITLE
builds static assets and start server error

### ISSUE THREAD

**Issue by ECHO-64** [javascript-tutorial/server#100]
C:\Users\**\Desktop
λ cd javascript.info/server

C:\Users\**\Desktop\javascript.info\server (master -> origin)
λ sh ./edit en
[03:29:55] Using gulpfile ~\Desktop\javascript.info\server\gulpfile.js
[03:29:55] Starting 'edit'...
[03:29:55] Starting 'webpack'...
[03:29:55] Starting 'engine:koa:tutorial:importWatch'...
[03:29:55] Starting 'livereload'...
[03:29:55] Starting 'server'...
(node:12044) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Livereload server listening
00:30:01.184Z  INFO application: Boot complete
00:30:01.254Z  INFO tutorialImporter: sync PLNKR_ENABLED=undefined
00:30:01.254Z  INFO tutorialImporter: sync C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js
C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info
00:30:01.256Z  INFO tutorialImporter: syncFolder C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js
00:30:01.258Z  INFO tutorialImporter: syncFolder C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\01-getting-started
00:30:01.260Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\01-getting-started\1-intro
00:30:01.322Z  INFO application: Server is listening localhost:3000
[03:30:01] Finished 'server' after 6.25 s
00:30:01.466Z  INFO tutorialImporter: importImage C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\01-getting-started\1-intro\limitations.svg to C:\Users\**\Desktop\javascript.info\server\public\en\article\intro
00:30:01.479Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\01-getting-started\2-manuals-specifications
00:30:01.676Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\01-getting-started\3-code-editors
00:30:02.349Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\01-getting-started\4-devtools
00:30:02.552Z  INFO tutorialImporter: importImage C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\01-getting-started\4-devtools\chrome.png to C:\Users\**\Desktop\javascript.info\server\public\en\article\devtools 00:30:02.556Z  INFO tutorialImporter: importImage C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\01-getting-started\4-devtools\chrome@2x.png to C:\Users\**\Desktop\javascript.info\server\public\en\article\devtools
00:30:02.561Z  INFO tutorialImporter: importImage C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\01-getting-started\4-devtools\safari.png to C:\Users\**\Desktop\javascript.info\server\public\en\article\devtools 00:30:02.566Z  INFO tutorialImporter: importImage C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\01-getting-started\4-devtools\safari@2x.png to C:\Users\**\Desktop\javascript.info\server\public\en\article\devtools
00:30:02.570Z  INFO tutorialImporter: syncFolder C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps
00:30:02.571Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\01-hello-world
00:30:02.999Z  INFO tutorialImporter: syncView: dir C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\01-hello-world\1-hello-alert\solution.view
00:30:03.425Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\02-structure
00:30:03.984Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\03-strict-mode
00:30:04.235Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\04-variables
00:30:04.626Z  INFO tutorialImporter: importImage C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\04-variables\variable-change.svg to C:\Users\**\Desktop\javascript.info\server\public\en\article\variables
00:30:04.631Z  INFO tutorialImporter: importImage C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\04-variables\variable.svg to C:\Users\**\Desktop\javascript.info\server\public\en\article\variables00:30:04.636Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\05-types
00:30:05.037Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\06-alert-prompt-confirm
00:30:05.315Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\07-type-conversions
00:30:05.592Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\08-operators
00:30:05.792Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\09-comparison
00:30:05.969Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\10-ifelse
00:30:06.551Z  INFO tutorialImporter: importImage C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\10-ifelse\2-check-standard\ifelse_task2.svg to C:\Users\**\Desktop\javascript.info\server\public\en\task\check-standard
00:30:06.566Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\11-logical-operators
00:30:06.879Z  INFO tutorialImporter: importImage C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\11-logical-operators\9-check-login\ifelse_task.svg to C:\Users\**\Desktop\javascript.info\server\public\en\task\check-login
00:30:06.885Z  INFO tutorialImporter: syncArticle C:\Users\**\Desktop\javascript.info\server\repo\en.javascript.info\1-js\02-first-steps\12-nullish-coalescing-operator
./tmp/en/styles.styl[
03:30:06Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
] ModuleBuildError: Module build failed (from ./node_modules/stylus-loader/index.js):'webpack' errored after 12 s
TypeError: Class constructor Visitor cannot be invoked without 'new'[
03:30:06    at new ImportVisitor (C:\Users\**\Desktop\javascript.info\server\node_modules\stylus-loader\lib\listimports.js:10:11)]
Error: ./tmp/en/styles.styl    at listImports (C:\Users\**\Desktop\javascript.info\server\node_modules\stylus-loader\lib\listimports.js:72:23)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):    at C:\Users\**\Desktop\javascript.info\server\node_modules\stylus-loader\lib\pathcache.js:295:15
ModuleBuildError: Module build failed (from ./node_modules/stylus-loader/index.js):    at tryCatchReject (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:840:30)
TypeError: Class constructor Visitor cannot be invoked without 'new'    at runContinuation1 (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:799:4)
    at new ImportVisitor (C:\Users\**\Desktop\javascript.info\server\node_modules\stylus-loader\lib\listimports.js:10:11)    at Fulfilled.when (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:590:4)
    at listImports (C:\Users\**\Desktop\javascript.info\server\node_modules\stylus-loader\lib\listimports.js:72:23)
 at Pending.run (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:481:13)
    at C:\Users\**\Desktop\javascript.info\server\node_modules\stylus-loader\lib\pathcache.js:295:15    at Scheduler._drain (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\Scheduler.js:62:19)

    at tryCatchReject (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:840:30)    at Scheduler.drain (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\Scheduler.js:27:9)
    at runContinuation1 (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:799:4)    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
    at Fulfilled.when (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:590:4)    at C:\Users\**\Desktop\javascript.info\server\node_modules\webpack\lib\NormalModule.js:316:20
    at Pending.run (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:481:13)
    at C:\Users\**\Desktop\javascript.info\server\node_modules\loader-runner\lib\LoaderRunner.js:367:11    at Scheduler._drain (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\Scheduler.js:62:19)
    at C:\Users\**\Desktop\javascript.info\server\node_modules\loader-runner\lib\LoaderRunner.js:233:18    at Scheduler.drain (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\Scheduler.js:27:9)
    at context.callback (C:\Users\**\Desktop\javascript.info\server\node_modules\loader-runner\lib\LoaderRunner.js:111:13)    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
    at tryCatchReject (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:840:30)    at C:\Users\**\Desktop\javascript.info\server\node_modules\webpack\lib\NormalModule.js:316:20
    at runContinuation1 (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:799:4)    at C:\Users\**\Desktop\javascript.info\server\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at Rejected.when (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:623:4)    at C:\Users\**\Desktop\javascript.info\server\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\**\Desktop\javascript.info\server\node_modules\loader-runner\lib\LoaderRunner.js:111:13)    at Pending.run (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:481:13)
    at tryCatchReject (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:840:30)    at Scheduler._drain (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\Scheduler.js:62:19)
    at runContinuation1 (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:799:4)
    at Scheduler.drain (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\Scheduler.js:27:9)    at Rejected.when (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:623:4)
    at Pending.run (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\makePromise.js:481:13)    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
    at Scheduler._drain (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\**\Desktop\javascript.info\server\node_modules\when\lib\Scheduler.js:27:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
    at formatError (C:\Users\**\Desktop\javascript.info\server\node_modules\gulp-cli\lib\versioned\^4.0.0\format-error.js:21:10)
    at Gulp.<anonymous> (C:\Users\**\Desktop\javascript.info\server\node_modules\gulp-cli\lib\versioned\^4.0.0\log\events.js:33:15)
    at Gulp.emit (node:events:526:35)
    at Gulp.emit (node:domain:489:12)
    at Object.error (C:\Users\**\Desktop\javascript.info\server\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (C:\Users\**\Desktop\javascript.info\server\node_modules\now-and-later\lib\map.js:50:14)
    at f (C:\Users\**\Desktop\javascript.info\server\node_modules\once\once.js:25:25)
    at f (C:\Users\**\Desktop\javascript.info\server\node_modules\once\once.js:25:25)
    at tryCatch (C:\Users\**\Desktop\javascript.info\server\node_modules\async-done\index.js:24:15)
    at done (C:\Users\**\Desktop\javascript.info\server\node_modules\async-done\index.js:40:12)
    at onError (C:\Users\**\Desktop\javascript.info\server\node_modules\async-done\index.js:51:5)
[03:30:07] 'edit' errored after 12 s

C:\Users\**\Desktop\javascript.info\server (master -> origin)
λ

**Comment by mostafa-nematpour** [comment]
I have this problem too
Did you find a way?

**Comment by kaellandrade** [comment]
I have this problem too.

**Comment by iliakan** [comment]
Please `git pull` latest and reinstall `npm i` node_modules.
