### ISSUE TITLE
Fail setup at step 6 `./edit en`

### ISSUE THREAD

**Issue by shallow-beach** [javascript-tutorial/server#106]
I am on up-to-date MacOS on ARM.

I followed the README, and get stuck at step 6 with the following error:

```
$ ./edit en                                         
TypeError: LRUCache is not a constructor
    at new RequestCaptureStream (/Users/shallow-beach/js-info/server/modules/engine/log/requestCaptureStream.js:37:23)
    at Object.<anonymous> (/Users/shallow-beach/js-info/server/modules/engine/log/streams.js:37:17)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/shallow-beach/js-info/server/modules/engine/log/index.js:23:15)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
```

I am just using the current master branch of [.info](../../en.javascript.info). Anyone bumped into this before?

**Comment by RyBhrdwj** [comment]
Yup, I encountered the same issue. You just need to fix the import statement.
Replace the import of 'lru-cache' in `/Users/shallow-beach/js-info/server/modules/engine/log/requestCaptureStream.js` with
`let LRUCache = require('lru-cache');`

**Comment by tarasyyyk** [comment]
Just add `"lru-cache": "^11.0.0"` to `package.json > "dependencies"`

**Comment by joaquinelio** [comment]
Novemer 2024 new machine fresh install

fixed that dependency 
only to get another problem another package

tried nvm node 19.something, didnt work.  I didnt try anything else 

Is the server working?
If yes, I'll collect data and ask again

**Comment by iliakan** [comment]
Fixed I hope =)
