### ISSUE TITLE
Cannot find module 'engine/koa/tutorial/repos'

### ISSUE THREAD

**Issue by HachemiH** [javascript-tutorial/server#31]
Hi,
After all changes with translations, i've decided to reinstall completely server and i got this error : 

```
internal/modules/cjs/loader.js:657
    throw err;
    ^

Error: Cannot find module 'engine/koa/tutorial/repos'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/Hachemi/sites/lab/js/server/modules/config/index.js:68:13)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
```

Did i miss something ?

**Comment by iliakan** [comment]
git pull and retry?

**Comment by HachemiH** [comment]
It's ok now thank you, but got the same problem i had before : the solutions links don't work, should i open a new issue for this little problem ?

**Comment by iliakan** [comment]
I'll review that issue, should have been fixed long ago.

**Comment by iliakan** [comment]
ah maybe I understand

It's on the local server only?

**Comment by iliakan** [comment]
on the "production" site everything's ok?

**Comment by HachemiH** [comment]
Yes it's only on the local server, on the production server all it's ok.

**Comment by iliakan** [comment]
Then it's fine, as development code is not uploaded to plnkr.
Probably we could upload it, but not sure it's needed.

**Comment by iliakan** [comment]
Closing this one, as the webserver seems to be working now, please reopen if it doesn't.

**Comment by HachemiH** [comment]
Hum, it's not the link to plnkr, it's the link to all "**solution.md**" for all task which is not working.

When we translate it, it's a little difficult to check our solution's translation without this link, it's not a big problem, but it was working good on previous versions.

**Comment by iliakan** [comment]
Please git pull:
1. server 
2. modules/engine

I fixed this and make solution open by default in edit mode.

**Comment by HachemiH** [comment]
All is good now many thanks.
