### ISSUE TITLE
Cannot find module 'translate'

### ISSUE THREAD

**Issue by colin3dmax** [javascript-tutorial/server#32]
```bash
$ ./edit en
[08:40:52] Using gulpfile ~/Downloads/test/js/server/gulpfile.js
[08:40:52] Starting 'webpack'...
[08:40:55] Starting 'engine:koa:tutorial:importWatch'...
[08:40:55] Starting 'livereload'...
[08:40:55] Starting 'server'...
[08:40:55] 'server' errored after 143 ms
[08:40:55] Error: Cannot find module 'translate'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/colin/Downloads/test/js/server/modules/engine/koa/tutorial/controller/task.js:8:23)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/colin/Downloads/test/js/server/modules/engine/koa/tutorial/router.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at module.exports (/Users/colin/Downloads/test/js/server/modules/engine/koa/lazyRouterMiddleware.js:8:34)
    at module.exports (/Users/colin/Downloads/test/js/server/modules/engine/koa/mountHandlerMiddleware.js:13:63)
    at Object.exports.init (/Users/colin/Downloads/test/js/server/modules/engine/koa/tutorial/index.js:21:11)

```

When I run `./edit en` I got the error above.
Should I need to install  translate  ?

**Comment by iliakan** [comment]
Please git pull. Ok now?
