### ISSUE TITLE
Can't run server.

### ISSUE THREAD

**Issue by ibragimof** [javascript-tutorial/server#35]
I've updated (git pull) local repository of server and english frontend. After updating sever not run with error (windows):

![Untitled-1](https://user-images.githubusercontent.com/47029060/58875765-d58e0d00-86e5-11e9-866f-e496e20ef176.png)
`
PS E:\js\server> ./edit en en

E:\js\server>call gulp edit   | bunyan
Cannot read property 'tasks' of undefined TypeError: Cannot read property 'tasks' of undefined
    at Orchestrator.add (E:\js\server\node_modules\orchestrator\index.js:54:8)
    at Object.<anonymous> (E:\js\server\gulpfile.js:21:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at execute (C:\Users\w4\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:28:18) undefined

E:\js\server>goto :eof
`

**Comment by iliakan** [comment]
Please `npm i -g gulp@4`, you seem to have 3.

**Comment by ibragimof** [comment]
I've updated gulp:
![Untitled-1](https://user-images.githubusercontent.com/47029060/58906760-1148c700-8726-11e9-93fc-aa9ca8441555.png)
And still getting the same error:

![Untitled-1](https://user-images.githubusercontent.com/47029060/58906815-3c331b00-8726-11e9-9e96-c4f216356bea.png)

**Comment by ibragimof** [comment]
I've update (pull) all repos and reinstall my Node.JS. Still can't run server (even it is actually new folder with new repos in it). Windows10(1903), Node.JS 10 (LTS from official web page)
