### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by Goudarz** [javascript-tutorial/server#46]
I followed instruction in README.
When I'm trying to start server with code:

` js/server$ ./edit en `

I got this error :

`
js/server$ ./edit en
[08:39:39] Using gulpfile /js/server/gulpfile.js
[08:39:39] Starting 'edit'...
[08:39:39] Starting 'webpack'...
[08:39:39] Starting 'engine:koa:tutorial:importWatch'...
[08:39:39] Starting 'livereload'...
[08:39:39] Starting 'server'...
(node:28882) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
05:09:42.609Z  INFO application: Boot complete
[08:39:42] 'engine:koa:tutorial:importWatch' errored after 3.55 s
[08:39:42] Error: ENOENT: no such file or directory, lstat '/js/en.javascript.info'
    at Object.realpathSync (fs.js:1454:7)
    at new TutorialImporter (/js/server/modules/engine/koa/tutorial/lib/tutorialImporter.js:26:20)
    at module.exports (/js/server/modules/engine/koa/tutorial/tasks/importWatch.js:20:18)
[08:39:42] 'edit' errored after 3.56 s
[08:39:42] The following tasks did not complete: webpack, livereload, server
[08:39:42] Did you forget to signal async completion?
`

as well as for `./edit ru ru`:

`
[09:13:10] 'engine:koa:tutorial:importWatch' errored after 17 s
[09:13:10] Error: Already exists an entry with slug:prototype-inheritance
    at TutorialTree.add (/js/server/modules/engine/koa/tutorial/models/tutorialTree.js:137:13)
    at TutorialImporter.syncArticle (/js/server/modules/engine/koa/tutorial/lib/tutorialImporter.js:229:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[09:13:10] 'edit' errored after 17 s
[09:13:10] The following tasks did not complete: livereload
[09:13:10] Did you forget to signal async completion?
`

**Comment by iliakan** [comment]
" Error: ENOENT: no such file or directory, lstat '/js/en.javascript.info'" - it can't fins the tutorial text.

Clone the tutorial text repo in there.

**Comment by mjfneto** [comment]
`[13:48:48] Error: Already exists an entry with slug:url at TutorialTree.add... at TutorialImporter.syncArticle....at processTicksAndRejections...at async TutorialImporter.syncFolder...at async TutorialImporter.sync...at async module.exports...[13:48:48] 'edit' errored after 39 s [13:48:48] The following tasks did not complete: livereload [13:48:48] Did you forget to signal async completion?`

Same?

**Comment by iliakan** [comment]
The tutorial is exactly from git or modified?

**Comment by mjfneto** [comment]
I believe it is the same mentioned in the tutorial on how to run the server locally to edit the tutorial, so I'd guess it is exactly from git.

**Comment by iliakan** [comment]
You follow the instruction, and the tutorial doesn't run?

**Comment by mjfneto** [comment]
Well, it's not happening as the tutorial describes it should.
