### ISSUE TITLE
module missing

### ISSUE THREAD

**Issue by ranimaniyan** [javascript-tutorial/server#54]
`[13:50:12] 'engine:koa:tutorial:importWatch' errored after 951 ms
[13:50:12] Error: Cannot find module 'mongoose'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/aequalis/Documents/my_passion/JS_ta-tranz/js/server/modules/engine/plunk/models/plunk.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/aequalis/Documents/my_passion/JS_ta-tranz/js/server/modules/engine/plunk/index.js:2:17)
[13:50:12] 'edit' errored after 955 ms
[13:50:12] The following tasks did not complete: webpack, livereload, server
[13:50:12] Did you forget to signal async completion?`

Unable to run the server and encountered an error with "cannot find 'mongoose' module". Since I installed npm V10+ and updated npm modules.

Note: uglifyjs-webpack-plugin was deprecated. So I installed terser-webpack-plugin

**Comment by iliakan** [comment]
Please try now.

P.S Don't pay attention to webpack plugins, we'll make a major update when webpack 5 is ready.
