### ISSUE TITLE
Server not working!

### ISSUE THREAD

**Issue by MuhammedZakir** [javascript-tutorial/server#67]
This is what I get when I do `./edit en`.

```
YError: Invalid second argument. Expected string or boolean but received object.
    at argumentTypeError (/Users/x/javascript-tutorial/server/node_modules/.pnpm/node_modules/yargs/lib/argsert.js:67:9)
    at /Users/x/javascript-tutorial/server/node_modules/.pnpm/node_modules/yargs/lib/argsert.js:49:39
    at Array.forEach (<anonymous>)
    at argsert (/Users/x/javascript-tutorial/server/node_modules/.pnpm/node_modules/yargs/lib/argsert.js:44:21)
    at Object.Yargs.self.usage (/Users/x/javascript-tutorial/server/node_modules/.pnpm/node_modules/yargs/yargs.js:455:5)
    at Object.<anonymous> (/Users/x/javascript-tutorial/server/node_modules/.pnpm/gulp@4.0.2/node_modules/gulp-cli/index.js:61:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)

/Users/x/javascript-tutorial/server/node_modules/.pnpm/node_modules/yargs/yargs.js:463
        throw new YError('.usage() description must start with $0 if being used as alias for .command()')
        ^
YError: .usage() description must start with $0 if being used as alias for .command()
    at Object.Yargs.self.usage (/Users/x/javascript-tutorial/server/node_modules/.pnpm/node_modules/yargs/yargs.js:463:15)
    at Object.<anonymous> (/Users/x/javascript-tutorial/server/node_modules/.pnpm/gulp@4.0.2/node_modules/gulp-cli/index.js:61:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/x/javascript-tutorial/server/node_modules/.pnpm/gulp@4.0.2/node_modules/gulp/bin/gulp.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
```

**Comment by iliakan** [comment]
Couldn't reproduce. Anyone else has that issue?

**Comment by MuhammedZakir** [comment]
It's pnpm's issue. Should have tried another tool before reporting! Sorry!
