### ISSUE TITLE
 Error: Already exists an entry with slug:primitive-conversions-questions

### ISSUE THREAD

**Issue by rodrigomarcell** [javascript-tutorial/server#79]
Getting this error when i run the command "edit pt" to start the server

 Error: Already exists an entry with slug:primitive-conversions-questions
    at TutorialTree.add (C:\Users\Marcell\Documents\Projetos\javascript.info\js\server\modules\engine\koa\tutorial\models\tutorialTree.js:140:13)
    at TutorialImporter.syncTask (C:\Users\Marcell\Documents\Projetos\javascript.info\js\server\modules\engine\koa\tutorial\lib\tutorialImporter.js:352:15)
    at TutorialImporter.syncArticle (C:\Users\Marcell\Documents\Projetos\javascript.info\js\server\modules\engine\koa\tutorial\lib\tutorialImporter.js:240:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async TutorialImporter.syncFolder (C:\Users\Marcell\Documents\Projetos\javascript.info\js\server\modules\engine\koa\tutorial\lib\tutorialImporter.js:150:9)
    at async TutorialImporter.syncFolder (C:\Users\Marcell\Documents\Projetos\javascript.info\js\server\modules\engine\koa\tutorial\lib\tutorialImporter.js:148:9)
    at async TutorialImporter.sync (C:\Users\Marcell\Documents\Projetos\javascript.info\js\server\modules\engine\koa\tutorial\lib\tutorialImporter.js:85:5)
    at async module.exports (C:\Users\Marcell\Documents\Projetos\javascript.info\js\server\modules\engine\koa\tutorial\tasks\importWatch.js:32:5)
[21:51:44] 'edit' errored after 6.47

What could be happening?

**Comment by iliakan** [comment]
There are two articles with a name `*-primitive-conversions-questions` (different number).

One of them should be deleted, please compare with English version.
