### ISSUE TITLE
Error: callback(): The callback was already called.

### ISSUE THREAD

**Issue by liudonghua123** [javascript-tutorial/server#91]
I followed the guidence on readme, but I got the following errors.

reproduce steps:
1. npm install -g bunyan gulp@4 cross-env
2. mkdir javascript-tutorial
3. cd javascript-tutorial
4. git clone https://github.com/javascript-tutorial/server
5. git clone https://github.com/javascript-tutorial/engine server/modules/engine
6. git clone https://github.com/javascript-tutorial/en.javascript.info server/repo/en.javascript.info
7. cd server
8. npm install
9. ./edit en # or use `cross-env PORT=8080 ./edit en`

```
D:\code\js\javascript-tutorial>ver

Microsoft Windows [Version 10.0.22621.819]

D:\code\js\javascript-tutorial>node -v
v18.12.0

D:\code\js\javascript-tutorial>npm -v
8.5.1

D:\code\js\javascript-tutorial>
D:\code\js\javascript-tutorial\server>cross-env PORT=8080 ./edit en

D:\code\js\javascript-tutorial\server>call gulp edit   | bunyan
[10:04:04] Using gulpfile D:\code\js\javascript-tutorial\server\gulpfile.js
[10:04:04] Starting 'edit'...
[10:04:04] Starting 'webpack'...
[10:04:04] Starting 'engine:koa:tutorial:importWatch'...
[10:04:04] Starting 'livereload'...
[10:04:04] Starting 'server'...
(node:17900) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Livereload server listening
[2022-11-11T02:04:35.436Z]  INFO: application/17900 on DESKTOP-DELL: Boot complete
[10:04:35] 'engine:koa:tutorial:importWatch' errored after 32 s
[10:04:35] Error: ENOENT: no such file or directory, lstat 'D:\code\js\javascript-tutorial\server\repo\"en".javascript.info'
    at Object.realpathSync (node:fs:2552:7)
    at new TutorialImporter (D:\code\js\javascript-tutorial\server\modules\engine\koa\tutorial\lib\tutorialImporter.js:24:20)
    at module.exports (D:\code\js\javascript-tutorial\server\modules\engine\koa\tutorial\tasks\importWatch.js:19:18)
[10:04:35] 'edit' errored after 32 s

D:\code\js\javascript-tutorial\server>goto :eof

D:\code\js\javascript-tutorial\server>
D:\code\js\javascript-tutorial\server>edit en

call gulp edit   | bunyan
[10:06:17] Using gulpfile D:\code\js\javascript-tutorial\server\gulpfile.js
[10:06:17] Starting 'edit'...
[10:06:17] Starting 'webpack'...
[10:06:17] Starting 'engine:koa:tutorial:importWatch'...
[10:06:17] Starting 'livereload'...
[10:06:17] Starting 'server'...
(node:21684) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Livereload server listening
[2022-11-11T02:06:21.138Z]  INFO: application/21684 on DESKTOP-DELL: Boot complete
[2022-11-11T02:06:21.184Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: sync PLNKR_ENABLED=undefined
[2022-11-11T02:06:21.184Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: sync D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js
D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js D:\code\js\javascript-tutorial\server\repo\en.javascript.info
[2022-11-11T02:06:21.186Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: syncFolder D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js
[2022-11-11T02:06:21.187Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: syncFolder D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js\01-getting-started
[2022-11-11T02:06:21.188Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: syncArticle D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js\01-getting-started\1-intro
[2022-11-11T02:06:21.215Z]  INFO: application/21684 on DESKTOP-DELL: Server is listening localhost:3000
[10:06:21] Finished 'server' after 4.17 s
[2022-11-11T02:06:21.266Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: importImage D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js\01-getting-started\1-intro\limitations.svg to D:\code\js\javascript-tutorial\server\public\en\article\intro
[2022-11-11T02:06:21.272Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: syncArticle D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js\01-getting-started\2-manuals-specifications
[2022-11-11T02:06:21.349Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: syncArticle D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js\01-getting-started\3-code-editors
[2022-11-11T02:06:21.830Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: syncArticle D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js\01-getting-started\4-devtools
[2022-11-11T02:06:21.926Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: importImage D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js\01-getting-started\4-devtools\chrome.png to D:\code\js\javascript-tutorial\server\public\en\article\devtools
[2022-11-11T02:06:21.930Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: importImage D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js\01-getting-started\4-devtools\chrome@2x.png to D:\code\js\javascript-tutorial\server\public\en\article\devtools
[2022-11-11T02:06:21.933Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: importImage D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js\01-getting-started\4-devtools\safari.png to D:\code\js\javascript-tutorial\server\public\en\article\devtools
[2022-11-11T02:06:21.936Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: importImage D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js\01-getting-started\4-devtools\safari@2x.png to D:\code\js\javascript-tutorial\server\public\en\article\devtools
[2022-11-11T02:06:21.939Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: syncFolder D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js\02-first-steps
[2022-11-11T02:06:21.939Z]  INFO: tutorialImporter/21684 on DESKTOP-DELL: syncArticle D:\code\js\javascript-tutorial\server\repo\en.javascript.info\1-js\02-first-steps\01-hello-world
[10:06:22] 'webpack' errored after 5.48 s
[10:06:22] Error: callback(): The callback was already called.
    at context.callback (D:\code\js\javascript-tutorial\server\node_modules\loader-runner\lib\LoaderRunner.js:106:10)
    at Object.<anonymous> (D:\code\js\javascript-tutorial\server\node_modules\css-loader\lib\loader.js:50:18)
    at D:\code\js\javascript-tutorial\server\node_modules\css-loader\lib\processCss.js:236:4
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:06:22] 'edit' errored after 5.48 s

goto :eof

D:\code\js\javascript-tutorial\server>
```

**Comment by iliakan** [comment]
Please install node.js v16.

You can find it at https://nodejs.org/dist/v16.18.1/.

**Comment by iliakan** [comment]
added workaround, please git pull and try again.

**Comment by iliakan** [comment]
Right, added this option to Windows .cmd file too =)

**Comment by iliakan** [comment]
Because Webpack uses these calls for hashing.
