### ISSUE TITLE
Project running error

### ISSUE THREAD

**Issue by Henry667** [javascript-tutorial/server#99]
Hello all,
I want to ran the jsinfo project locally in my window machine, after following all commands from this page [Page ](https://github.com/javascript-tutorial/server).

When i ran this command ./edit en. I got following errors

```
[2023-09-03T13:38:02.548Z]  INFO: tutorialImporter/7160 on SunnyNegi: syncArticle C:\Users\91964\jsinfio\server\repo\en.javascript.info\1-js\02-first-steps\13-while-for
./tmp/en/styles.styl
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/stylus-loader/index.js):
TypeError: Class constructor Visitor cannot be invoked without 'new'
    at new ImportVisitor (C:\Users\91964\jsinfio\server\node_modules\stylus-loader\lib\listimports.js:10:11)
    at listImports (C:\Users\91964\jsinfio\server\node_modules\stylus-loader\lib\listimports.js:72:23)
    at C:\Users\91964\jsinfio\server\node_modules\stylus-loader\lib\pathcache.js:295:15
[19:08:02]     at tryCatchReject (C:\Users\91964\jsinfio\server\node_modules\when\lib\makePromise.js:840:30)
'webpack' errored after 4.65 s
    at runContinuation1 (C:\Users\91964\jsinfio\server\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\91964\jsinfio\server\node_modules\when\lib\makePromise.js:590:4)
[19:08:02]     at Pending.run (C:\Users\91964\jsinfio\server\node_modules\when\lib\makePromise.js:481:13)
Error: ./tmp/en/styles.styl
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/stylus-loader/index.js):
TypeError: Class constructor Visitor cannot be invoked without 'new'
```

**Comment by Antipula** [comment]
Hi guys. I have a similar error.
nodejs 16, 18, 20
Debian 12, Windows 10.

**Comment by mostafa-nematpour** [comment]
I have this problem too

**Comment by iliakan** [comment]
Try with the latest version, reopen if needed.
